# Generated by Django 4.0.3 on 2022-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
