# Generated by Django 4.0.3 on 2022-05-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecosystem.course'),
        ),
        migrations.AddField(
            model_name='task',
            name='uploaded_task',
            field=models.FileField(default=None, upload_to='tasks/'),
        ),
    ]
