# Generated by Django 4.0.3 on 2022-05-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_task_course_task_uploaded_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.student')),
            ],
        ),
    ]
