# Generated by Django 4.0.3 on 2022-05-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0003_coursestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_file', models.FileField(upload_to='submissions')),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uploaded_task',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecosystem.teacher'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='CourseStudent',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.student'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.task'),
        ),
        migrations.AddField(
            model_name='coursemembers',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.course'),
        ),
        migrations.AddField(
            model_name='coursemembers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosystem.student'),
        ),
    ]
